### ISSUE TITLE
Web User Bug Reports

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#640] opened 2019-03-17 12:07 UTC
Please select which platform you are using:-
Desktop Version

Feedback Type
Bug Reports

What went wrong?
SSA ji

when we click on next page from the first page of search,  it does not take to next page, it takes to diffrent page, it happened when i searched for Aarti, Please check
 
What should have happened instead?

    
How can the issue be recreated by our team?
when we click on next page from first page of search,  it does not take to next page, it takes to diffrent page, it happened when i searched for Aarti, Please check

Which web browser are using?
FireFox 

Operating System
Microsoft Windows

Name
Anuwinder Singh

**Comment by bogas04** [comment] 2019-04-11 18:00
Couldn't reproduce ☹️

**Comment by tarunsingh5** [comment] 2019-04-11 18:01
closing since it could not be replicated

**Closed by tarunsingh5** 2019-04-11 18:01 UTC
Labels: user-reports
