### ISSUE TITLE
Web User Bug Reports

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#751] opened 2019-07-31 01:00 UTC
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
when you click on the next page of the results it just keep displaying the first page results 
 
What should have happened instead?
whe you click the next page button of search results it should display the next page and not the same first page over and over again
    
How can the issue be recreated by our team?
dont know

Which web browser are using?
Safari 12.1.2 (13607.3.10)

Operating System
Mac OS

Name
sukhwinder singh

**Comment by Gauravjeetsingh** [comment] 2019-07-31 06:36
Closing it. Duplicate of #741

**Closed by Gauravjeetsingh** 2019-07-31 06:36 UTC
Labels: user-reports
