### ISSUE TITLE
Web User Bug Reports

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#601] opened 2019-01-09 02:30 UTC
Please select which platform you are using:-
Desktop Version

Feedback Type
Bug Reports

What went wrong?
The daily Hukamnava is the same for me for the past week or so.
 
What should have happened instead?
A different Shabad
    
How can the issue be recreated by our team?
That the daily hukamnava is correct to the day

Which web browser are using?
Chrome 

Operating System
Mac OS

Name
Shiv D

**Comment by bogas04** [comment] 2019-01-10 06:40
Duplicate of #45

**Closed by bogas04** 2019-01-10 06:40 UTC
Labels: user-reports
