### ISSUE TITLE
Web User not working

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#468] opened 2018-05-20 21:21 UTC
Please select which platform you are using:-
Web Version

Feedback Type
not working

What went wrong?
the site shows the webpage of not workingfuntion properly , I guess
 
What should have happened instead?
it should atleast show home page
    
How can the issue be recreated by our team?
by fixing it

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Bibekbir khalsa

**Comment by bogas04** [comment] 2018-05-22 04:47
Possibly duplicate of #365

**Closed** 2018-06-09 11:03 UTC
Labels: user-reports
