### ISSUE TITLE
Meta tags for shabads should contain shabad name and translations

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#594] opened 2018-12-19 03:08 UTC
ShabadName is available now for each shabad, sort of like an article title. Use this for better SEO

**Comment by bogas04** [comment] 2018-12-19 17:11
Can you share the API/contract?

**Comment by bogas04** [comment] 2018-12-19 17:12
Closing as this is duplicate of #49

**Closed by bogas04** 2018-12-19 17:12 UTC

**Comment by ManjotS** [comment] 2018-12-19 19:45
@Divjot Singh <bogas04@gmail.com> this isnt a duplicate, this is a separate
issue we wanted done later. Set by aman singh
