### ISSUE TITLE
Web User Bug Reports

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#761] opened 2019-08-02 12:13 UTC
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
Uff respond 
Your search option has error
 
What should have happened instead?
Theek karo 
Hun menu puchoge ki
    
How can the issue be recreated by our team?
🤦‍♀️

Which web browser are using?
Chrome 

Operating System
Other

Name
Gurdeep  Singh

**Comment by tarunsingh5** [comment] 2019-08-02 16:59
duplicate of #760

**Closed by tarunsingh5** 2019-08-02 16:59 UTC
Labels: user-reports
