### ISSUE TITLE
Web User Comments

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#652] opened 2019-04-24 16:02 UTC
when i search full word translation english of SSGGSJ, for the term 'word of the shabad' on the desktop im getting 32 pages with 20 searches per page.

the same search on the mobile device is also yielding 20 searches per page but only 4 pages .

Please select which platform you are using:-
Desktop Version

Feedback Type
Comments

What went wrong?

 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
bahadur  singh

**Comment by Gauravjeetsingh** [comment] 2019-04-24 16:46
Full word translation English of SSGGSJ gives zero results on both desktop and mobile.

Tried other search modes as well, it gave the same number of results on desktop and mobile. So not sure how to reproduce this issue.

**Comment by tarunsingh5** [comment] 2019-04-24 23:52
closing this issue since we dont manage the app

**Closed by tarunsingh5** 2019-04-24 23:52 UTC
Labels: user-reports
