### ISSUE TITLE
Web User Bug Reports

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#981] opened 2020-02-20 17:29 UTC
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
The Sikhi To the Max web page has not been showing any information for over a week now. It does not show the search bar or anything else other than the title
 
What should have happened instead?

    
How can the issue be recreated by our team?
Opening up Sikhi to the Max page on Chrome version : 
Version 79.0.3945.130 (Official Build) (64-bit)

Which web browser are using?
Chrome 79.0.3945.130

Operating System
Microsoft Windows

Name
Milan Kaur

**Comment by tarunsingh5** [comment] 2020-02-28 21:03
duplicate of #983

**Closed** 2020-02-28 21:03 UTC
Labels: user-reports
