### ISSUE TITLE
Hukamnama does not update appropriately

### ISSUE THREAD

**Issue by inderpreet99** [KhalisFoundation/sttm-web#161] opened 2017-07-21 05:04 UTC
I'm from the EST timezone. It is currently July 21th, 2017 at 1:00 am. I noticed that the hukamnama page has not been updated to the latest from [sgpc.net](http://sgpc.net/daily-mukhwak-pdf/): ਤੁਮ ਦਾਤੇ ਠਾਕੁਰ ਪ੍ਰਤਿਪਾਲਕ ਨਾਇਕ ਖਸਮ ਹਮਾਰੇ ॥

Below is listed as the current hukamnama from https://www.sikhitothemax.org/hukamnama, which is the hukamnama from July 20th, 2017. I think we're off by a day. Would be nice to show the dates on that page to let everyone know what they're looking at. Thanks.

```
ਟੋਡੀ ਮਹਲਾ ੫ ॥
Todee, Fifth Mehla:
ਸਾਧਸੰਗਿ ਹਰਿ ਹਰਿ ਨਾਮੁ ਚਿਤਾਰਾ ॥
In the Saadh Sangat, the Company of the Holy, I contemplate the Name of the Lord, Har, Har.
ਸਹਜਿ ਅਨੰਦੁ ਹੋਵੈ ਦਿਨੁ ਰਾਤੀ ਅੰਕੁਰੁ ਭਲੋ ਹਮਾਰਾ ॥ ਰਹਾਉ ॥
```

**Comment by ManjotS** [comment] 2018-01-16 21:37
is this still an issue @navdeepsinghkhalsa

**Comment by tarunsingh5** [comment] 2018-01-29 00:34
works in chrome and edge but not in FF

**Comment by bogas04** [comment] 2019-01-10 06:40
Duplicate of #45

**Closed by bogas04** 2019-01-10 06:40 UTC
Labels: 1️⃣, 🔥banidb, 🚫Blocked
