### ISSUE TITLE
Get rid of 404 Images

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#711] opened 2019-06-13 18:25 UTC
Please select which platform you are using:-
Web Version

Feedback Type
Enhancements

What went wrong?
Please improve the 404 image - https://www.sikhitothemax.org/assets/images/Sach%20Kaur.png
 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
Amandeep Singh

**Comment by tarunsingh5** [comment] 2019-07-19 19:55
why did you close this? this is a request that multiple users have had

**Comment by bogas04** [comment] 2019-07-23 16:34
Duplicate of #466

**Closed by bogas04** 2019-07-23 16:34 UTC
Labels: user-reports
