### ISSUE TITLE
Search Operators and Highlighting not working

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-web#988] opened 2020-02-28 20:44 UTC
https://stg.sikhitothemax.org/search?q=kIrqn%20%2B%20rhwau&type=2&source=all

Should highlight both words but highlights first word and next two words

**Comment by ManjotS** [comment] 2020-02-28 21:05
please assign to @turbanpanda

**Comment by Gauravjeetsingh** [comment] 2020-04-13 11:33
Need the API to show results with search operators. The highlighting part is done and deployed to prod.

**Comment by tarunsingh5** [comment] 2020-04-15 16:38
@Manjot Singh <manjot@manjotsingh.net> whats the update here

**Comment by ManjotS** [comment] 2020-04-15 16:54
I don't understand what the API needs to do here

**Comment by tarunsingh5** [comment] 2020-04-15 16:56
please sync w/ Gaurav directly

**Comment by ManjotS** [comment] 2020-04-15 16:57
thats what I am doing. @Gauravjeetsingh what does the API need to do here? Can you make an API ticket with your requirements?

**Comment by Gauravjeetsingh** [comment] 2020-04-16 06:42
@ManjotS veerji, I am not sure the root cause, maybe a newer deployment is needed. Search operators still give 0 results with the Banidb API. But they work fine in Khajana API.

BaniDB API with 0 search results: https://api.banidb.com/v2/search/hj*r?source=all&page=1
Khajana API with search results: https://api.khajana.org/v2/search/hj*r?source=all&page=1

**Comment by manjot** [comment] 2020-04-16 08:54
Why am I in this email thread?

Kindly exclude my email address.

**Comment by Gauravjeetsingh** [comment] 2020-04-27 05:32
It's working on prod now. Closing this up.

**Closed by Gauravjeetsingh** 2020-04-27 05:32 UTC
Labels: 1️⃣, 🚫Blocked
